const AUTH_SERVICE_URL = process.env.NEXT_PUBLIC_AUTH_SERVICE_URL;
const USER_SERVICE_URL = process.env.NEXT_PUBLIC_USER_SERVICE_URL;
const EVENT_SERVICE_URL = process.env.NEXT_PUBLIC_EVENT_SERVICE_URL;
const BOOKING_SERVICE_URL = process.env.NEXT_PUBLIC_BOOKING_SERVICE_URL;

export default { AUTH_SERVICE_URL, USER_SERVICE_URL, EVENT_SERVICE_URL, BOOKING_SERVICE_URL };
